import { useState } from 'react';

import Navbar from '../components/Navbar';
import Status from '../components/Status';
import QueryBox from '../components/QueryBox';
import SearchBar from '../components/SearchBar';
import AnswerBox from '../components/AnswerBox';
import Microphone from '../components/Microphone';

import './Home.css';

const Home = () => {

    const [query, setQuery] = useState('');
    const [status, setStatus] = useState(0);
    const [answer, setAnswer] = useState('This is a dummy answer generated by GPT. Please do not read this answer seroiusly as it may lead to wastage of time, frustration, boredom, anger, serious injuries or death. Also if you are still reading thank you for being a test subject. 👍');

    return (
        <div className='Home'>
            <Navbar />
            <SearchBar />
            <Status status={status} />
            <QueryBox status={status} query={query} setQuery={setQuery} />
            <AnswerBox answer={answer} />
            <Microphone status={status} setStatus={setStatus} />
        </div>
    );
}

export default Home;
